name: Reviewdog

on:
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  gofmt:
    name: Go Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: find . -not -path '*/\.git/*' -type f -name '*.go' -exec gofmt -s -w {} \+
      - uses: reviewdog/action-suggester@951f8ea45137fd52d269d75bddc3a813b78487aa

  whitespace:
    name: Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: find . -not -path '*/\.git/*' -type f -not -name '*.go' -exec sed -i 's/[[:space:]]\{1,\}$//' {} \+
      - uses: reviewdog/action-suggester@951f8ea45137fd52d269d75bddc3a813b78487aa
